version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
     - "8080:8080"
    environment:
     - KEYCLOAK_USER=keycloak
     - KEYCLOAK_PASSWORD=password
     - DB_VENDOR=POSTGRES
    depends_on:
     - postgres
    networks:
     - keycloak-network
  postgres:
    image: postgres
    environment:
     - POSTGRES_DB=keycloak
     - POSTGRES_USER=keycloak
     - POSTGRES_PASSWORD=password
    networks:
     - keycloak-network
networks:
  keycloak-network:
    driver: bridge
